<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJV6JZK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJV6JZK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJV6JZK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJV6JZK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXJV6JZK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XJV6JZK',
    'container.build_id' => '8d986ef4',
    'container.build_time' => 1560933120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJV6JZK');
